name: C CI

on:
  push:
    branches: [ * ]
  pull_request:
    branches: [ * ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: autoconf
      run: autoconf
    - name: configure
      run: ./configure
    - name: make
      run: make
